development:
  adapter: postgresql
  user: postgres
  password: 5treetLegal17
  encoding: unicode
  database: pinboard
  pool: 5
  timeout: 5000
  host:  localhost

test:
  adapter: postgresql
  database: pinboard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  user: postgres
  password: 5treetLegal17
  database: pinboard
  pool: 5
  timeout: 5000