development:
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: false
  database: pinboard_development
  pool: 5
  username: pbuser
  password: pbU5er123
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: false
  database: pinboard_test
  pool: 5
  username: pbuser
  password: pbU5er123
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: false
  database: pinboard_production
  pool: 5
  username: pbuser
  password: pbU5er123
  socket: /var/run/mysqld/mysqld.sock