# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28b438713de14db587f259f3fbb5a68ffdd9ab03cceeca4cae5120832fc83be35cf8e2e607ec202c2453b6d67c974cb11a002ed4372d0c6ea2cfc3cb76ccedd8

test:
  secret_key_base: 4b7613e72c92b9e80eea8f175dd38c06e1c2d73a0bfe520d3251d7481176a48816809d06c9a9aa609d96d3135c748defb2f0ac61bad80f2920351085752f8263

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
